"""add created_by to contacts

Revision ID: 2bc4d4c31817
Revises: 001
Create Date: 2026-03-10 19:42:54.687854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc4d4c31817'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, so we add as nullable and set default using existing data
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contacts_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_foreign_key('fk_contacts_created_by_user_id', 'users', ['created_by_user_id'], ['id'])

    # Set existing contacts' created_by_user_id to their current owner_user_id
    op.execute('UPDATE contacts SET created_by_user_id = owner_user_id WHERE created_by_user_id IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contacts_created_by_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contacts_created_by_user_id'))
        batch_op.drop_column('created_by_user_id')
    # ### end Alembic commands ###
